version: '3.3'
services:
  api:
    container_name: 'api'
    build: './'
    ports:
      - '9000:9000'
      - '9001:9001'
      - '9002:9002'
    volumes:
      - './:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'